import { ApplicationConfig, ApplicationIds } from "@/types/config";
import { DescriptionBlock } from "@/types/description";
import { Metadata } from "next";
import { createToolStructuredData } from "@/util/structuredDataUtils";

const navigationUrl = "/tools/random-number-generator";
const pageTitle = "Random Number Generator - Generate Random Numbers";
const pageDescription =
  "Generate random numbers instantly with our free tool. Perfect for lottery, gaming, passwords, and statistical sampling. Customizable range.";
const imageUrl = `${process.env.SCREENSHOTS_BASE_URL}/tools/random-number-generator.png`;

const keywords =
  "random number generator,random generator,number picker,lottery number generator,random picker,dice roller";

export const metadata: Metadata = {
  alternates: {
    canonical: `${process.env.HOSTNAME}${navigationUrl}`,
  },
  title: pageTitle,
  description: pageDescription,
  keywords,
  metadataBase: new URL(
    process.env.NODE_ENV === "development"
      ? "http://localhost:3000"
      : "https://webtoolseasy.com"
  ),
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon_48.png", sizes: "48x48" },
      { url: "/favion_512.png", sizes: "512x512" },
    ],
    shortcut: "/favicon.ico",
    apple: "/favicon.png",
  },
  openGraph: {
    title: pageTitle,
    type: "website",
    url: `${process.env.HOSTNAME}${navigationUrl}`,
    images: [
      {
        url: imageUrl,
        secureUrl: imageUrl,
        alt: pageTitle,
      },
    ],
    description: pageDescription,
  },
  twitter: {
    card: "summary_large_image",
    site: "@webtoolseasy",
    title: pageTitle,
    description: pageDescription,
    images: [imageUrl],
  },
  authors: {
    name: "Gaurav Kumar Yadav",
  },
  robots: "index, follow",
};

export const componentConfig: ApplicationConfig = {
  mainHeading: "Random Number Generator: Generate Random Numbers Instantly",
  navigationUrl,
  pageTitle,
  tags: keywords.split(",").map((word) => word.trim()),
  relatedTools: [
    ApplicationIds.PASSWORD_GENERATOR,
    ApplicationIds.UUID_VERSION4_GENERATOR,
  ],
  structuredData: createToolStructuredData({
    pageUrl: "random-number-generator",
    pageTitle,
    mainHeading: "Random Number Generator: Generate Random Numbers Instantly",
    keywords: keywords.split(",").map((word) => word.trim()),
  }),
};

export const descriptionData: DescriptionBlock[] = [
  {
    heading: "What is a Random Number Generator?",
    blockData: [
      "A random number generator (RNG) is a tool that produces unpredictable numbers within a specified range. It uses algorithms to generate numbers that have no pattern or predictability, making them truly random. Random numbers are essential in many applications from gaming and lotteries to cryptography and statistical sampling.",
    ],
  },
  {
    heading: "Why Use Our Random Number Generator?",
    listData: [
      "True randomness: Uses cryptographically secure random number generation.",
      "Customizable range: Set any minimum and maximum values.",
      "Multiple numbers: Generate single or multiple random numbers at once.",
      "No duplicates option: Ensure unique numbers when needed.",
      "Instant results: Generate numbers with a single click.",
      "Free to use: No registration or limitations.",
      "Privacy focused: All generation happens in your browser.",
    ],
  },
  {
    heading: "Common Uses of Random Number Generator",
    listData: [
      "Lottery numbers: Pick random numbers for lottery tickets.",
      "Gaming: Generate dice rolls, random encounters, or game mechanics.",
      "Contests and giveaways: Randomly select winners fairly.",
      "Statistical sampling: Choose random samples from populations.",
      "Decision making: Let chance decide when you can't choose.",
      "Password generation: Create random number components for passwords.",
      "Educational purposes: Teach probability and statistics concepts.",
      "Random assignments: Distribute tasks or groups randomly.",
    ],
  },
  {
    heading: "How to Use the Random Number Generator",
    listData: [
      "Set minimum value: Enter the lowest number in your range.",
      "Set maximum value: Enter the highest number in your range.",
      "Choose quantity: Specify how many random numbers to generate.",
      "Select uniqueness: Toggle whether numbers can repeat.",
      "Click generate: Get your random numbers instantly.",
      "Generate again: Create new sets as many times as needed.",
    ],
  },
  {
    heading: "Types of Random Number Generation",
    listData: [
      "True random numbers: Generated from physical phenomena (hardware-based).",
      "Pseudo-random numbers: Generated by algorithms that simulate randomness.",
      "Cryptographically secure: Special algorithms suitable for security applications.",
      "Uniformly distributed: Each number in range has equal probability.",
    ],
  },
  {
    heading: "Features of Our Random Number Generator",
    listData: [
      "Flexible ranges: From single digits to large numbers.",
      "Batch generation: Create multiple numbers at once.",
      "Unique mode: Prevent duplicate numbers in results.",
      "Copy function: Easy copying of generated numbers.",
      "History: View previously generated numbers.",
      "Fast performance: Instant generation without delays.",
    ],
  },
  {
    heading: "Random Number Generator vs Dice",
    blockData: [
      "Traditional dice are limited to specific ranges (1-6, 1-20, etc.), while a random number generator can work with any range you specify. RNG is also faster, can generate multiple numbers simultaneously, and ensures true statistical randomness. Physical dice may have bias due to weight distribution or rolling technique.",
    ],
  },
  {
    heading: "Fair Play and Randomness",
    blockData: [
      "Our random number generator uses JavaScript's crypto.getRandomValues() method when available, which provides cryptographically strong random values. This ensures fairness and unpredictability, making it suitable for applications where true randomness is important. The generator has no patterns or biases, giving each number an equal chance of selection.",
    ],
  },
];
