import { ApplicationConfig } from 'src/app/@types/config';
import { DescriptionBlock } from 'src/app/@types/description';

export const componentConfig: ApplicationConfig = {
  mainHeading: 'Online UUID Generator',
  subHeading: 'Generate UUID V4 & V1 For Free',
  navigationUrl: '/tools/uuid',
  pageTitle: 'Online UUID Generator',
  metaTags: [
    {
      name: 'description',
      content:
        'UUID Generator | Generate UUID | Online UUID Generator | Generate UUID V4 | Generate UUID V1 | Bulk UUID Generator',
    },
    {
      name: 'author',
      content: 'Gaurav Kumar Yadav',
    },
    { name: 'robots', content: 'index, follow' },
  ],
  tags: [
    'uuid',
    'uuid v4 generator',
    'uuid v1 generator',
    'online uuid generator',
    'generate uuid',
    'bulk uuid generator',
  ],
  icons: [
    {
      iconName: 'app-icon',
      iconRelativeUrl: 'app-icon.svg',
    },
    {
      iconName: 'linkedin-icon',
      iconRelativeUrl: 'linkedin-icon.svg',
    },
    {
      iconName: 'facebook-icon',
      iconRelativeUrl: 'facebook.svg',
    },
  ],
};

export const descriptionData: DescriptionBlock[] = [
  {
    heading: 'What is UUID Version 4?',
    blockData: [
      `A version 4 UUID is a randomly generated 128-bit identifier. As in other UUIDs, 4 bits are used to indicate version 4, and 2 bits are used to indicate the variant. Thus, 6 bits are constant, leaving 122 bits for the randomly generated part, for a total of 2122 (5.3×1036, 5.3 undecillion) possible values.`,
    ],
  },
  {
    heading: 'What is UUID Version 1?',
    blockData: [
      `Version-1 is based on the current time and the MAC address for the computer or "node" generating the UUID.`,
    ],
  },
  {
    heading: 'What is UUID ( Universally unique identifier )?',
    blockData: [
      `A UUID is a standardized method of generating unique identifiers for resources or objects in a computer system. These identifiers are designed to be unique across time and space, making them ideal for use in a variety of applications, such as database systems, network protocols, and software libraries.`,
      `The unique identifier generated by a UUID is typically represented as a string of characters, often in the format of xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, where each x is a hexadecimal digit. This combination of randomness and the use of a standard format makes UUIDs an effective way of ensuring that identifiers are unique even when generated in different systems or at different times.`,
      `UUIDs are especially useful in distributed systems, where multiple systems need to coordinate to manage resources, and in applications that need to generate unique identifiers without a centralized coordination mechanism.`,
      `In summary, UUID is a powerful tool for resource and object identification within a system, providing a standardized and effective way of generating unique identifiers that are unique across time and space.`,
    ],
  },
  {
    heading: 'Disclaimer',
    blockData: [
      `All the UUIDs are generated locally in browser only. Genearted UUIDs are provided as is without any warranty.`,
    ],
  },
];
