import { ApplicationConfig } from 'src/app/@types/config';
import { DescriptionBlock } from 'src/app/@types/description';
import { environment } from 'src/environments/environment';
import { AppDisplayNames } from 'src/environments/tools-directory-config';

const navigationUrl = '/tools/uuid-v1-generator';
const pageTitle = 'UUID Generator | Bulk UUID Generator | Unique Id Generation';
const pageDescription =
  'UUID generator tool lets you generate random/unique universally unique identifiers (UUID). Generate UUID version 1 (v1).';
const imageUrl = `${environment.screenshotsBaseUrl}/uuid-v1-generator.png`;

export const componentConfig: ApplicationConfig = {
  mainHeading: 'Online UUID Generator',
  subHeading: 'Generate UUID Version 1 (V1) Online',
  navigationUrl,
  pageTitle,
  metaTags: [
    {
      name: 'description',
      content: pageDescription,
    },
    {
      name: 'author',
      content: 'Gaurav Kumar Yadav',
    },
    { name: 'robots', content: 'index, follow' },
    {
      property: 'og:title',
      content: pageTitle,
    },
    { property: 'og:type', content: 'website' },
    { property: 'og:url', content: `${environment.hostname}${navigationUrl}` },
    { property: 'og:image', content: imageUrl },
    { property: 'og:image:secure_url', content: imageUrl },
    { property: 'og:description', content: pageDescription },
    { property: 'og:site_name', content: 'WebToolsEasy' },
    { property: 'twitter:card', content: 'summary_large_image' },
    { property: 'twitter:site', content: '@webtoolseasy' },
    { property: 'twitter:title', content: pageTitle },
    { property: 'twitter:description', content: pageDescription },
    { property: 'twitter:image', content: imageUrl },
  ],
  tags: [
    'uuid',
    'uuid v1 generator',
    'online uuid generator',
    'generate uuid',
    'bulk uuid generator',
  ],
  icons: [
    {
      iconName: 'jwt-icon',
      iconRelativeUrl: 'jwt-icon.svg',
    },
    {
      iconName: 'uuid-icon',
      iconRelativeUrl: 'uuid-icon.svg',
    },
  ],
  relatedTools: [
    {
      applicationId: 'jwt',
      displayText: AppDisplayNames.JWT_DECODER,
      iconName: 'jwt-icon',
      navigateUrl: '/tools/jwt',
    },
    {
      applicationId: 'uuidv4',
      displayText: AppDisplayNames.UUID_VERSION4_GENERATOR,
      iconName: 'uuid-icon',
      navigateUrl: '/tools/uuid-v4-generator',
    },
    {
      applicationId: 'guid',
      displayText: AppDisplayNames.GUID_GENERATOR,
      iconName: 'uuid-icon',
      navigateUrl: '/tools/guid-generator',
    },
  ],
};

export const descriptionData: DescriptionBlock[] = [
  {
    heading: 'What is Version 4 UUID?',
    blockData: [
      `A version 4 UUID is a randomly generated 128-bit identifier. As in other UUID, 4 bits are used to indicate version 4, and 2 bits are used to indicate the variant. Thus, 6 bits are constant, leaving 122 bits for the randomly generated part, for a total of 2122 (5.3×1036, 5.3 undecillion) possible values.`,
    ],
  },
  {
    heading: 'What is Version 1 UUID?',
    blockData: [
      `Version 1 is based on the current time and the MAC address for the computer or "node" generating the UUID.`,
    ],
  },
  {
    heading: 'What is UUID ( Universally unique identifier )?',
    blockData: [
      `A UUID is a standardized method of generating unique identifiers for resources or objects in a computer system. These identifiers are designed to be unique across time and space, making them ideal for use in a variety of applications, such as database systems, network protocols, and software libraries.`,
      `The unique identifier generated by a UUID is typically represented as a string of characters, often in the format of xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, where each x is a hexadecimal digit. This combination of randomness and the use of a standard format makes UUIDs an effective way of ensuring that identifiers are unique even when generated in different systems or at different times.`,
      `UUIDs are especially useful in distributed systems, where multiple systems need to coordinate to manage resources, and in applications that need to generate unique identifiers without a centralized coordination mechanism.`,
      `In summary, UUID is a powerful tool for resource and object identification within a system, providing a standardized and effective way of generating unique identifiers that are unique across time and space.`,
    ],
  },
  {
    heading: 'Key Features',
    listData: [
      `Unlimited UUID generation for free`,
      `Generate UUIDs in bulk using bulk UUID generator tool and export UUIDs in a text file`,
      `Security: All the UUIDs are generated in host browser only`,
    ],
  },
  {
    heading: 'Disclaimer',
    blockData: [
      `Generated UUIDs are provided as is without any kind of warranty.`,
    ],
  },
  {
    heading: 'References',
    links: [
      {
        displayText: 'Read more about UUIDs at Wikipedia',
        url: 'https://en.wikipedia.org/wiki/Universally_unique_identifier',
      },
      {
        displayText: 'RFC 4122',
        url: 'https://www.ietf.org/rfc/rfc4122.txt',
      },
    ],
  },
];
