import type { Metadata } from "next";
import "./globals.css";
import { robotoFont } from "@/design";
import { theme } from "@/theme";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoFont.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <div className="main-container no-vr-scroll">
              {/* <ResponsiveAppBar>
                <FlexList
                  items={topAppBarItems}
                  isDirectionRow={true}
                ></FlexList>
              </ResponsiveAppBar>
              <MenuItems
                menuItems={categoryData}
                sx={{
                  marginTop: "10px",
                }}
              /> */}
              <div
                className="base-container full-width flex-full-height"
                style={{
                  overflowY: "auto",
                }}
              >
                {children}
              </div>
              {/* <ResponsiveAppBar position="relative" /> */}
            </div>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
